refactored and zapped explicit 127 exit status

diff --git a/isjson b/isjson
--- a/isjson
+++ b/isjson
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 #  Synopsis:
-#	Are files well formed json?
+#	Is a file or standard input well formed json?
 #  Usage:
 #	isjson <x.json
 #	isjson x.json
@@ -9,27 +9,48 @@
 #	0	input is well formed json
 #	1	input is not well formed json
 #	2	unknown error
-#	127	python can not be executed
+#  Note:
+#	Extend to more than one file!
 #
 
-python -m json.tool $@ >/dev/null 2>&1 | read OUT
-STATUS=${PIPESTATUS[*]}
-case "$STATUS" in
-'0 0')
-	echo "YES: valid json"
-	exit 0
+die()
+{
+	echo "ERROR: $@" >&2
+	exit 2
+}
+
+case $# in
+0)
 	;;
-'1 0'|'1 1')
-	echo "NO: invalid json"
-	exit 1
-	;;
-'127 '*)
-	echo "ERROR: exit status=127: is python installed?"
-	exit 127
+1)
+	#  sadly, file existence exit with status 1
+	test -r $1 || die "can not read file: $1"
 	;;
 *)
-	STATUS=$(echo $STATUS | cut -d' ' -f1)
-	echo "ERROR: python json failed: exit status=$STATUS: $OUT" >&2
-	exit $STATUS
+	die "wrong number of arguments: got $#, expected < 2"
 	;;
 esac
+
+python -m json.tool $1 >/dev/null 2>&1
+STATUS=$?
+case $STATUS in
+0)
+	ANSWER="YES: valid"
+	;;
+1)
+	ANSWER="NO: invalid"
+	;;
+127)
+	die "exit status=127: is python installed?"
+	;;
+*)
+	die "python json failed: exit status=$STATUS"
+	;;
+esac
+
+if [ $# = 0 ];  then
+	echo "$ANSWER json"
+else
+	echo "$ANSWER json: $1"
+fi
+exit $STATUS
