improved logging for new mac security

diff --git a/launchd-log b/launchd-log
--- a/launchd-log
+++ b/launchd-log
@@ -25,7 +25,7 @@ PROG=$(basename $0)
 
 log()
 {
-	echo "$PROG: $(date +'%Y/%m/%d %H:%M:%S'): $@"
+	echo "$(date +'%Y/%m/%d %H:%M:%S'): $@"
 }
 
 die()
@@ -40,13 +40,20 @@ PROG="$PROG: $(basename $1)"
 log "hello, world"
 trap 'log good bye, cruel world' EXIT TERM INT QUIT
 
-log "working directory: $(pwd)"
+CWD=$(pwd)		#  for security issue in new mac os
+STATUS=$?
+test $? = 0 || die "cwd failed: exit status=$STATUS"
+test -n "$CWD" || die 'empty output from pwd command'
+
+log "working directory: $CWD"
 
 CONF=etc/launchd-log.conf
 log "launchd config: $CONF"
 if [ -r $CONF ];  then
 	log "sourcing config file ..."
 	. $CONF || exit
+else
+	log 'no config (ok)'
 fi
 
 log 'dump of process environment ...'
