replace option --template witch action template

diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -77,7 +77,7 @@
 #
 #	Think deepky about recursive version that can combine *.dist files
 #
-#	Rename variable PRODUCT to less ambitious REPO.
+#	Rename variable PRODUCT to less ambitious REPO or even DIST_TAR
 #
 #	What does "copy_files BASEs mean?
 #
@@ -105,7 +105,7 @@
 #
 
 PROG=$(basename $0)
-USAGE="$PROG [--help] [--template] <distribution-file>"
+USAGE="$PROG <help | template | tar> [distribution-file]"
 
 help()
 {
@@ -142,9 +142,9 @@ Description:
 
 		$PRODUCT-YYYYMMDD_HHmm.tar.bz2.
 
-	where PRODUCT is the $(basename $(pwd)).  To change the basename of
-	the product, define the PRODUCT environment variable in the
-	configuration file.
+	where default PRODUCT is the $(basename <dist> .dist).
+	To change the basename of the product, define the PRODUCT environment
+	variable in the configuration file.
 
 		PRODUCT=setspace
 
@@ -290,18 +290,15 @@ make_dir()
 
 test $# = 0 && die "wrong number of arguments"
 
-#
-#  Read the configuration file.
-#
-case "$1" in
-'')
-	die "wrong number of argument"
-	;;
---help)
+ACTION="$1";  shift
+case "$ACTION" in
+help)
 	help
 	exit 0
 	;;
---template)
+
+
+template)
 	cat <<END
 #
 #  Synopsis:
@@ -400,25 +397,34 @@ SBINs="
 END
 	exit 0
 	;;
--*)
-	die "unknown option: $1"
+tar)
+	ACTION="$1";  shift
+	;;
+*.dist)
+	DIST="$ACTION"
+	test -r "$DIST" || die "can't read dist file: $DIST"
 	;;
 *)
-	CONF="$1"
-	test -r "$CONF" || die "can't read configuration file: $CONF"
+	test -e "$ACTION" && die "dist file does not end in .dist: $ACTION"
+	die "unknown action: $ACTION"
 	;;
 esac
+
+DIST="$ACTION"
+test -r "$DIST" || die "can't read dist file: $DIST"
+
+#  Write a compresed tar file of the dist files.
 
 #
 #  Source in the configuration file.
 #
-. ./$CONF
+. ./$DIST
 
 #
 #  PRODUCT is basename of directory, by default;
 #  otherwise, whatever is set in the configuration file.
 #
-PRODUCT=${PRODUCT:=$(basename $(pwd))}
+PRODUCT=${PRODUCT:=$(basename $DIST .dist)}
 
 echo "# product is $PRODUCT"
 
