fixed bug in unpacking single dist tars

diff --git a/make-dist.d/make-dist-tar b/make-dist.d/make-dist-tar
--- a/make-dist.d/make-dist-tar
+++ b/make-dist.d/make-dist-tar
@@ -1,56 +1,17 @@
 #!/usr/bin/env bash
 #
 #  Synopsis:
-#	Build a tar using files/dirs defined in shell sourcable config file.
+#	Libexeced by make-dist to assemble a tar file for a single directory.
 #  Usage:
-#	make-dist --help
-#	make-dist --template >foobar.dist
-#	vi foobar.dist
-#
-#	make-dist foobar.dist
-#	D=$(pwd)
-#	cd /usr/local/foobar && tar xvf $D/foobar-20140403_1213.tar.bz2
-#
-#	#  Makefile variables can be extracted from the the root.dist file
-#	#  with these recipes.  Example make code follows:
-#
-#		DIST=product.dist
-#		COMPILEs := $(shell  (. ./$(DIST) && echo $$COMPILEs))
-#		SBINs := $(shell  (. ./$(DIST) && echo $$SBINs))
-#		LIBs := $(shell  (. ./$(DIST) && echo $$LIBs))
-#		SRCs := $(shell  (. ./$(DIST) && echo $$SRCs))
-#		INCLUDEs := $(shell  (. ./$(DIST) && echo $$INCLUDEs))
-#
-#	Config variables to create directories bit not touch contents are:
-#
-#		ARCHIVE=""
-#		ATTIC=""
-#		BINs="[files] ..."
-#		CACHE=""
-#		CGIBINs="[files] ..."
-#		DATA=""
-#		DIST=""
-#		ETC=""
-#		HTDOCSs="[files] ..."
-#		LIBEXECs="[files] ..."
-#		LIBs="[files] ..."
-#		LOG=""
-#		RUN=""
-#		SBINs="[files] ..."
-#		SPOOL=""
-#		SRCs="[files] ..."
-#		TMP=""
-#		SYM
-#
-#	Empty string implies directory is created, if needed.
-#	Any files
-#
+#	make-dist tar <path/to.dist>
 #  See:
 #	https://github.com/jmscott/work/blob/master/make-dist
 #	https://en.wikipedia.org/wiki/Unix_filesystem
+#  Requires:
+#	gnu sed
+#	jmscott elapsed-english
+#	gnu date
 #  Note:
-#	Add startup test for GNU sed!
-#
 #	- VAR->dir remaps only for a single directory.  for example,
 #
 #		LIBs->lib/schema
@@ -61,17 +22,12 @@
 #	must be hand coded.  Adding an option to generate the install
 #	recipes would be nice:
 #
-#		make-dist dynamic-dirs
+#		make-dist dirs-recipe
 #
 #	Which could be manually spliced back into the Makefile.
-#
-#	- Add command "env" or "fs" to document environment variables in config
-#	file that describe directories.
 #	
-#	Think deepky about recursive version that can combine *.dist files
-#
 #	Why are the dirs/ for copy_file() hardwired for BINs, SBINs, etc?
-#	Should not thast list be derived from the dist file?
+#	Should not that list be derived from the dist file?
 #
 #	Add "unpack" action, which properly removes and unpacks *.tar.bz2
 #	directories.  Will need to make no assumptions about the root directory
@@ -84,25 +40,43 @@
 #	target.
 #
 
-leave()
-{
-	if [ -n "$WORK_TMP" -a -d $WORK_TMP ];  then
-		rm -rf $WORK_TMP					||
-			echo "WARN: rm work tmp failed: exit status=$?"
-	fi
-}
-
-trap leave EXIT QUIT TERM
+PROG='make-dist-tar'
+START_EPOCH=$(date +%s)
+DIST=
+WORK_TMP=
 
 die()
 {
 	echo "$PROG: ERROR: $@" >&2
-	echo "usage: $USAGE"
 	exit 1
 }
 
 [ "${BASH_VERSINFO:-0}" -ge 4 ] 					||
 	die "bash version must be >= 4: ver ${BASH_VERSINFO:-0}" 
+
+WARN()
+{
+	echo "$PROG: WARN: $@" >&2
+}
+
+leave()
+{
+	if [ -n $WORK_TMP -a -d $WORK_TMP ];  then
+		echo "--$WORK_TMP"
+		chmod -R +w $WORK_TMP					||
+			WARN "chmod +w tmp/work failed: exit status=$?"
+		find $WORK_TMP ! -type l -print | xargs chmod +w
+		rm -rf $WORK_TMP || WARN "rm work tmp failed: exit status=$?"
+	fi
+	echo "#  $PROG: good bye, cruel world: $(elapsed-english $START_EPOCH)"
+}
+trap leave EXIT QUIT TERM
+DIST=$1;  shift
+PROG="$PROG: $DIST"
+
+echo
+echo "#  $PROG:  hello, world"
+
 
 #  map directory name to create permisions.
 
@@ -128,6 +102,7 @@ declare -A dir2perm=(
 )
 
 #  map directory name to copy file permisions.
+
 declare -A file2perm=(
 	[bin]='ug=rx,o='
 	[cgi-bin]='ug=rx,o='
@@ -140,6 +115,7 @@ declare -A file2perm=(
 )
 
 #  map VAR name to directory name
+
 declare -A VAR2dir=(
 	[ARCHIVE]='archive'
 	[ATTIC]='attic'
@@ -161,10 +137,10 @@ declare -A VAR2dir=(
 	[TMP]='tmp'
 )
 
-declare -A VAR2dir_local
+#  user dist file can override the mapping from a vars, like LIBs,
+#  to the default directory.
 
-PROG=$(basename $0)
-USAGE="$PROG <help | template | tar> [product.dist]"
+declare -A VAR2dir_local
 
 is_readable()
 {
@@ -182,11 +158,10 @@ make_SYMLINKs()
 	for S in $SYMLINKs;  do
 		echo $S | fgrep -e '->' | sed 's/->/ /' | while read A B;  do
 		echo "+$B -> $A" && (
-			cd $WORK_TMP				||
-				die "cd symlink failed: exit status=$?"
+			cd $WORK_TMP || die "cd symlink failed: exit status=$?"
 			BD=$(dirname $B)
 			if [ ! -d $BD ];  then
-				echo "+$BD"
+				echo "+>$BD"
 				#  no permisions!!!
 				mkdir -p $BD				||
 					die 'make_SYMLINKs: mkdir failed: '\
@@ -222,8 +197,8 @@ copy_file()
 	#
 	#  Make the staging directory.
 	#
-	echo "+$DIR"
-	mkdir -p $WORK_TMP/$DIR				||
+	echo "+>$DIR"
+	mkdir -p $WORK_TMP/$DIR						||
 		die "copy_file: mkdir stage root failed: exit status=$?"
 	#
 	#  Copy the files and directories into the staging directory
@@ -234,9 +209,9 @@ copy_file()
 		#  so just make the directory.
 		#
 		if [ -d $F ];  then
-			echo "+$DIR/$F/"
+			echo "+>$DIR/$F/"
 			DN=$WORK_TMP/$DIR/$F
-			mkdir -p $DN					||
+			mkdir -p "$DN"					||
 				die "copy_file: mkdir config failed: "	\
 					"exit status=$?"
 			continue
@@ -246,9 +221,9 @@ copy_file()
 		#  The file lives in an uncreated directory.
 		#
 		DN=$(dirname $F | sed "s:^$DIR\/::" | sed "s:^$DIR$::")
-		if [ "$DN" -a ! -d $WORK_TMP/$DIR/$DN ];  then
-			echo "+$DIR/$DN/"
-			D="$WORK_TMP/$DIR/$DN"
+		if [ -n "$DN" -a ! -d $WORK_TMP/$DIR/$DN ];  then
+			echo "+>$DIR/$DN/"
+			D=$WORK_TMP/$DIR/$DN
 			mkdir -p $D					||
 				die "copy_file: mkdir failed: exit status=$?"
 		fi
@@ -269,7 +244,8 @@ copy_file()
 		#  Ought to check fo existence of file before copy?
 		#
 		echo ">$D/$(basename $F)"
-		cp $F $WORK_TMP/$D || die "copy_file: cp failed: exit status=$?"
+		cp $F $WORK_TMP/$D					||
+			die "copy_file: cp failed: exit status=$?"
 	done
 
 	#  set the permissions in the work temp directory
@@ -314,45 +290,16 @@ make_dir()
 	#
 	#  Make the staging directory.
 	#
-	#  Note:  need to test for error!
-	#
-	mkdir -p $WORK_TMP/$DIR || die "make_dir: mkdir failed: exit status=$?"
+	echo "+>$WORK_TMP/$DIR"
+	mkdir -p $WORK_TMP/$DIR						||
+		die "make_dir: mkdir failed: exit status=$?"
 	find $WORK_TMP/$DIR -type d -print | xargs chmod $PERMD
 	STATUS=${PIPESTATUS[*]}
 	test "$STATUS" = '0 0' ||
 		die "make_dir: find dir | chmod failed: status=$STATUS"
 }
 
-test $# = 0 && die "wrong number of arguments"
-
-ACTION="$1";  shift
-case "$ACTION" in
-help)
-	exec $JMSCOTT_ROOT/libexec/make-dist-help
-	exit 0
-	;;
-
-
-template)
-	exec cat $JMSCOTT_ROOT/lib/make-dist-template.dist
-	exit 0
-	;;
-tar)
-	ACTION="$1";  shift
-	;;
-*.dist)
-	DIST="$ACTION"
-	;;
-*)
-	test -e "$ACTION" && die "dist file does not end in .dist: $ACTION"
-	die "unknown action: $ACTION"
-	;;
-esac
-
-DIST="$ACTION"
 test -r "$DIST" || die "can't read dist file: $DIST"
-
-#  Write a compresed tar file of the dist files.
 
 #
 #  Source in the configuration file.
@@ -400,10 +347,10 @@ is_readable SBINs
 #
 #  Make temporary work directory.
 #
-WORK_TMP=tmp/$PROG.$$
+WORK_TMP=${TMPDIR:=/tmp}/make-dist-tar.$$
 test -d $WORK_TMP && die "tmp directory $WORK_TMP already exists"
+echo "+>$WORK_TMP"
 mkdir -p $WORK_TMP || die "mkdir -p $WORK_TMP failed"
-echo ">$WORK_TMP"
 
 #  make directories, if variables defined in distribution file
 
@@ -449,7 +396,7 @@ make_SYMLINKs
 #  Tar up files into $TAR_FILE-YYYYMMDD_hhmm.tar.bz2
 #
 TAR_FILE=$TAR_FILE-$(date +'%Y%m%d_%H%M').tar.bz2
-echo ">$TAR_FILE"
+echo ">>$TAR_FILE"
 (
 	cd $WORK_TMP || die "cd $WORK_TMP failed"
 	#
@@ -465,18 +412,4 @@ test "$STATUS" = '0 0'							||
 
 test -s $TAR_FILE || die "empty tar file $TAR_FILE"
 
-#
-#  Zap the temporary scratch dir.
-#
-#  Note:
-#	What about zapping dir tmp/ upon certain common errors,
-#	like missing files.
-#
-echo "-$WORK_TMP"
-find $WORK_TMP ! -type l -print | xargs chmod +w
-STATUS="${PIPESTATUS[*]}"
-test "$STATUS" = '0 0' || die "find work tmp dir | chmod +w failed: "	\
-			      "exit status=$?"
-
-rm -rf $WORK_TMP || die "rm -rf $WORK_TMP failed"
 exit 0
diff --git a/make-dist.d/make-dist-tars b/make-dist.d/make-dist-tars
--- a/make-dist.d/make-dist-tars
+++ b/make-dist.d/make-dist-tars
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
 #  Synopsis:
-#	Merge multiple tar files into a single tar file.
+#	Libexecs script to merge multiple tar files into a single tar file.
 #  Description:
 #	Merge the files from several different *.dist files into a single
 #	tar file suitable for deployment.  The merged tar file can be unpacked
@@ -26,20 +26,22 @@
 #	tar xvf dist/$TAR
 #	#  start processes for setcore and pdfbox
 #  Requires:
-#	gnu "realpath" command
-#	gnu "find" command with regex
-#	gnu "bash" version 5
-#	gnu "tar"
+#	gnu realpath find bash tar date
+#	jmscott elapsed-english
 #	
 #  Exit Status:
 #	0	tars merged into single tar <tag>-YYYYMMDD_hhmm.tar.bz2
 #	1	failure
 #  Note:
+#	Consider moving the individual tar files into the respective dirs/dist.
+#
 #	Extract the name of the individual tar file from the new var
 #	$TAR_FILE_BASE in the *.dist file.
 #
 
 PROG=make-dist-tars
+START_EPOCH=$(date +%s)
+TAG=
 WORK_TMP=
 START_DIR=$(pwd)
 TAR_BZ2_REGEX='-[123][0-9]{7}_[0-5][0-9]{3}[.]tar[.]bz2$'
@@ -47,26 +49,33 @@ TAR_BZ2_REGEX='-[123][0-9]{7}_[0-5][0-9]{3}[.]tar[.]bz2$'
 #  map dist base to realpath of containing directory
 declare -A tarbz2dir_path
 
-log()
+WARN()
 {
-	echo "$PROG: $@"
+	PREAMBLE=$PROG
+	test -n "$TAG" && PREAMBLE="$PREAMBLE-$TAG"
+	echo "$PREAMBLE: WARN: $@" >&2
+}
+
+zap_work_tmp()
+{
+	test -n "$WORK_DIR" -a -d $WORK_DIR || return
+	cd "$START_DIR"
+	"-$WORK_TMP"
+	rm -rf $WORK_TMP || WARN "rm tmp/work/ failed: exit status=$?"
+	WORK_TMP=
 }
 
 leave()
 {
-	if [ -n "$XWORK_TMP" -a -d "$WORK_TMP" ];  then
-		cd "$START_DIR"
-		"-$WORK_TMP"
-		rm -rf "$WORK_TMP"					||
-			log "WARN: rm work dir failed: exit status=$?"
-		WORK_TMP=
-	fi
-	echo '!good bye, cruel world'
+	zap_work_tmp
+	echo "#  $PROG: good bye, cruel world: $(elapsed-english $START_EPOCH)"
 }
 
 die()
 {
-	log "ERROR: $@" >&2
+	PREAMBLE="$PROG"
+	test -n "$TAG" && PREAMBLE="$PREAMBLE-$TAG"
+	echo "$PREAMBLE: ERROR: $@" >&2
 	exit 1
 }
 
@@ -116,7 +125,7 @@ make_dist_tar()
 
 	for TAR in $(find_dist_tar $BASE_DIST);  do
 		mv $TAR $WORK_TMP/dist				||
-			die "mv tar to work-tmp/dist failed: exit status=#?"
+			die "mv tar to tmp/work/dist failed: exit status=#?"
 
 		local _TAR
 		_TAR=$(basename $TAR)
@@ -127,40 +136,37 @@ make_dist_tar()
 
 unpack_dist_tar()
 {
-	local _PATH
-	local _TAR
+	local TAR_NAME
+	local TAR_PATH
+	local DIST_PATH
 
-	_TAR=$(basename $TAR)
+	cd $WORK_TMP || die "cd work/tmp start unpack failed: exit status=$?"
+	TAR_PATH=$1
+	TAR_NAME=$(basename $TAR_PATH)
+	echo "꛷$TAR_PATH"
 
-	_PATH="${tarbz2dir_path[$_TAR]}"
-	echo "+$_PATH"
-	mkdir -p $_PATH || die "mkdir unpack failed: exit status=$?"
-	echo "꛷$TAR"
-	tar xvf $TAR
+	DIST_PATH="${tarbz2dir_path[$TAR_NAME]}"
+	test -n "$DIST_PATH" || die "can not find dist path: $TAR_NAME"
+	echo "+>$DIST_PATH"
+	mkdir -p $DIST_PATH || die "mkdir unpack dist failed: exit status=$?"
+
+	TAR_PATH=$(realpath --relative-to $DIST_PATH $TAR_PATH)
+	cd $DIST_PATH || die "cd unpack dist path failed: exit status=$?"
+	tar xvf $TAR_PATH || die "tar x unpack failed: exit status=$?"
 }
 
 #  verify paths to dist files
 
 trap leave EXIT
+echo
+echo "#  $PROG: hello, world"
 
 TAG="$1";  shift
-case "$TAG" in
-*' '*)
-	die "space not allowed in tag: $TAG"
-	;;
-*.dist)
-	die "expected tag, got a dist file: $TAG"
-	;;
-*.*)
-	die "tag contains a period char: $TAG"
-	;;
-esac
-
 
 #  verify the dist files exist
 
 for DIST in $*;  do
-	case "$DIST" in
+	case $DIST in
 	*' '*)
 		die "space not allowed in dist path: $DIST"
 		;;
@@ -179,11 +185,11 @@ done
 #  files.
 WORK_TMP=${TMPDIR:=/tmp}/$PROG-$$.d
 echo "+>$WORK_TMP/dist"
-mkdir -p "$WORK_TMP"/dist || die "mkdir -p work-tmp/dist failed: exit status=$?"
+mkdir -p $WORK_TMP/dist || die "mkdir -p tmp/work/dist failed: exit status=$?"
 
 WORK_TMP=$(realpath $WORK_TMP)
 
-#  build a tar file for each dist file by executing "make dist" in thel
+#  build a tar file for each dist file by executing "make dist" in the
 #  containing directory.
 
 for DIST in $*;  do
@@ -194,13 +200,14 @@ echo "->$WORK_TMP"
 cd $WORK_TMP || die "cd work tmp failed: exit status=$?"
 
 for TAR in dist/*.tar.bz2;  do
-	unpack_dist_tar $TAR
+	unpack_dist_tar $TAR || exit
 done
 
-tar cf - $(ls | fgrep -vw dist)				|
-	bzip2 >$START_DIR/$TAG-$(date +'%Y%m%d_%H%M').tar.bz2
+cd $WORK_TMP || die "cd work/tmp post unpack failed: exit status=$?"
 
-STATUS="${PIPESTATUS[*]}"
-test "$STATUS" = '0 0' || die "tar cf work/tmp failed: exit status=$STATUS"
+#  bundle the temp directory into single tar in $START_DIR
+
+tar cf $START_DIR/$TAG-$(date +'%Y%m%d_%H%M').tar.bz2 . --bzip2		||
+	die "tar tmp/work failed: exit status=$?"
 
 exit 0
